### PR TITLE
Fix for Add `Select From List Item Popup Menu` keyword #118

### PR DESCRIPTION
**Pull request by badari412**

### CODE REVIEW

**Comment by badari412** [comment]
My fix has nothing to do with "Get Current Context With Dialog" test which failed. So can someone please tell me how do I rerun the travis job ?

**Comment by mihaiparvu** [comment]
Thank you for the PR @badari412! I think you need admin permissions on the repository to manually re-run the tests. Did that for your PR and the test passes now.

**Comment by badari412** [comment]
> Thank you for the PR @badari412! I think you need admin permissions on the repository to manually re-run the tests. Did that for your PR and the test passes now.

Thank you! Can you please review my changes?

**Comment by badari412** [comment]
> Please remove unnecessary spacing in this line ` ListOperator listOperator = createOperator(identifier);`

Thanks! Pushed the latest changes after corrections.

**Comment by badari412** [comment]
> @badari412 Thanks for your PR . There would be one change that should be done. Could you update the acceptance test to something like `Select From Popup Menu` https://github.com/robotframework/SwingLibrary/blob/master/src/test/resources/robot-tests/menu.robot .

Isn't the test file you mentioned just for "Menu" related tests? Adding list popup menu test here goes against the design followed currently. Anyway, I added the acceptance test related to the change I made in "list.robot" file.

**Comment by cristii006** [comment]
> > @badari412 Thanks for your PR . There would be one change that should be done. Could you update the acceptance test to something like `Select From Popup Menu` https://github.com/robotframework/SwingLibrary/blob/master/src/test/resources/robot-tests/menu.robot .
> 
> Isn't the test file you mentioned just for "Menu"(Main menu) related tests? Adding list popup menu test here goes against the design followed currently. Anyway, I added the acceptance test related to the change I made in "list.robot" file.

@badari412 Yes `Select From PopupMenu` is indeed for menu but can you create a test similar to it, by using the new implemented keyword? The problem with the old test is that it doesn't verify in any way the result of the output.

**Pull request merged**
