### PR TITLE
add keywords to call methods from custom components

### PR DESCRIPTION
**Pull request by WojtekKowaluk**
We add generic getters which can be used to read data from custom controls.

### CODE REVIEW

**Comment by jussimalinen** [comment]
Looks good, but I'm a bit hesitant about creating different keywords for each different argument combination. I think calling with strings and booleans at least might be necessary in future.

Couldnt we make this more generic and just make it "call component method" which takes *args and converts them automatically?

Then we can use the argument converter from javalibcore (included in swinglibrary). https://github.com/robotframework/JavalibCore/blob/master/src/main/java/org/robotframework/javalib/reflection/ArgumentConverter.java

I suppose we could just assume that there are no overloaded methods and that there will only be one method with specific name? Another approach would be that we try to choose the method with the same number of arguments as the call has. (But I'm happy with going with a simpler solution first, if that works for you).

**Comment by jussimalinen** [comment]
Also we really should have atleast some tests for this feature.

**Comment by WojtekKowaluk** [comment]
Actually I was already thinking about it. Getting method with right number of arguments is not problem at all. I will update this PR soon.

Making some tests based on existing test app should not be problem either.

**Comment by WojtekKowaluk** [comment]
i have updated PR. Keyword now takes list of argument, and coverts them to requires types. Only problem with approach this solution is when there are method overloads with same number of arguments (but different argument types). But i think this is quite rare case in real life. I Also added some tests.

**Comment by jussimalinen** [comment]
This is very good. getMethodByNameAndArgumentCount helper can I think stay where it is until it is needed somewhere else. I think it would be slightly cleaner to add a helper private String getMethodDescription or something like that. But I can do that.

**Comment by jussimalinen** [comment]
Hum, the documentation actually could have been improved. I already made a release, but I will improve the docs for next one. At least some examples would be nice.

**Comment by WojtekKowaluk** [comment]
Right, totally forgot about it. I will take care of it if you don't mind.

**Comment by jussimalinen** [comment]
That should do it.

**Pull request merged**
