### PR TITLE
add support for TableTree tables

### PR DESCRIPTION
**Pull request by WojtekKowaluk**
We add support for tables that use JTree as cell rendered. This is common technique to create so called TreeTables as explained here:
http://www.comp.nus.edu.sg/~cs3283/ftp/Java/swingConnect/tech_topics/tables-trees/tables-trees.html
Before this patch, accessing a cell from column which represents tree structure results in Exception.

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Could the new/fixed functionality be tested? @jussimalinen is better to look at the code and comment this PR otherwise when his back at the office tomorrow.

**Comment by WojtekKowaluk** [comment]
hello,

Actually I'm already preparing email to him where i ask about idea how it
should be tested. this email will include internal details about how this
functionalitity is used in nokia so I hope together we can come with
approprite tests.

regards,
wojtek

**Comment by jussimalinen** [comment]
Could we just add a new table with JTree as cell renderer to the test application: https://github.com/robotframework/SwingLibrary/blob/master/src/main/java/org/robotframework/swing/testapp/TestApplication.java

Then we could access an element of that table to test this change? I think it would be good to have some acceptance test for this.

**Comment by jussimalinen** [comment]
The acceptance test could be added to this suite: https://github.com/robotframework/SwingLibrary/blob/master/src/test/resources/robot-tests/tablekeywords.txt

**Comment by WojtekKowaluk** [comment]
OK, i will do it.

**Comment by WojtekKowaluk** [comment]
I made test case (just grabbed some example from internet actually) and there is huge problem. It works okay also without my patch. Seems application we are testing is broken, not SwingLibrary itself. Seems getValueAt method at model is not working in our application. This method is not used during normal application usage, but it is called from Robot. So after all, this patch is nothing more than workaround around broken getValueAt method in our app. I think we will try to request fix in our app.

**Comment by jussimalinen** [comment]
Okay, good find. If you can get it fixed in the application it would be much better. I will leave this pull request open if you find anything else while fixing the app, but now it seems like this should be closed without merging.

**Pull request closed without merging**
